### ISSUE TITLE
Broken link to meeting-guide-json.php in README

### ISSUE THREAD

**Issue by tintinnabulate** [code4recovery/spec#14]
README.md links to https://github.com/code4recovery/spec/blob/master/meeting-guide-json.php , which is a broken link.

(See https://github.com/code4recovery/spec/blame/df38ca151dd1cb9e896ee2cb2e7c30a8d3780050/README.md#L11 for the specific commit & line I'm talking about)

**Comment by tintinnabulate** [comment]
Whilst I'm at it...

The page https://meetingguide.org/validate has a bunch of broken links in the footer:

* Android App: https://play.google.com/store/apps/details?id=org.meetingguide.app
* GitHub: https://github.com/meeting-guide
* Twitter: https://twitter.com/meetingguide

**Comment by joshreisner** [comment]
Thanks for the heads-up
