### ISSUE TITLE
validator not refreshing json file

### ISSUE THREAD

**Issue by HowardL-md** [code4recovery/spec#15]
HI, We use a .json file for our feed to MG and I try to check it using the validator to make sure it's being excepted.
I have found that it's a one shot deal. Once I ask it to check our url it will not refresh with a recheck. This happens if I have an error the first go around or not. It seems to take 24 hours or so for it to get a fresh copy and then it will not get another for probably another 24. I can change a character in a meeting name or something and it will not be reflected in a "check feed".

For example I went to check our .json yesterday and I got an error because of a matching slug. I fixed and tried again and got the same error. I changed a character in a name x and retried - same error , no changed character. I tried again (about 24 hours later) and got validated, but then changed a character and retried and got no change!

I can syntax check the .json using my Firefox browser either at the url or using file>open and changes are usually reflected but yesterday I'm pretty sure that was stuck too.  Today that is not a problem. 

So I suppose this is some kind of caching issue somewhere out there but it is not conducive to a good experience:) I wondered if anyone else experiences this and if there is some workaround. 

Howard();

**Comment by joshreisner** [comment]
Hi @HowardL-md, please email appsupport@aa.org for issues with the Meeting Guide app, thanks
