### ISSUE TITLE
Create a contributions field

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/spec#16]
Creation of a generic contribution array field, accepting entries consisting of 2 specific entries.
type = enumerated : possible types >> "paypal","google","apple","venmo" << expansion would be easy - just adding to list here and to reference pointer below.

reference : string >> this is the account/handle name reference for the account.
based on the type - would know to call up specific url for service and then insert the handle info at the proper place.

example,
	"contributions":	[
		{
			"type":"paypal"
			"reference":"123a4567-3ea5-4e11-a5efc-123456789012" << paypal account # or appropriate reference 
		},
		{
			"type":"venmo"
			"reference":"ABSI_area72" << venmo account # or appropriate reference
		},
	],

code would see <type> was referenced and go through listing or appropriate locations,
upon finding correct location reference would then insert reference pointer properly

so ....
a = [{type : paypal , url : 'https://this-is-a-paypal-address.paypal.com/accounts/{}'}]
where a[i]['type'] == 'paypal':
url = a[i]['url'].format(contributions[0]['reference'])
then url would be returned as "https://this-is-a-paypal-address.paypal.com/accounts/123a4567-3ea5-4e11-a5efc-123456789012" for utilization ....

**Comment by joshreisner** [comment]
Hi, we currently have venmo, paypal, and square fields for contributions and are happy to add additional options. We want to keep the structure flat to accommodate people using spreadsheets. Also it’s possible and likely that some groups may use multiple services. 

PayPal values should be PayPal.me urls however.
