### ISSUE TITLE
JSON Validator processes meetings differently to the App

### ISSUE THREAD

**Issue by tintinnabulate** [code4recovery/spec#18]
Currently, a meeting that is "valid" according to the Validator is not necessarily "valid" in the App. This points to a deviation from the spec.

Example: The feed validator reports 589 meetings for <https://aa-london.com/api/meetingguide.json>. However, only ~120 meetings show up in the MeetingGuide app.

**Comment by tech2serve** [comment]
Is there some specific error you're saying that makes you think this is related to the spec? If you're not getting errors (well, outside of the number of meetings showing up in the app), then my first guess would be the issue isn't related to the spec.

In most cases, not seeing the number of meetings you expect to see in the app is caused by settings GSO controls. They set certain filter and geographical points that control what meetings from a feed show up.

Please contact appsupport@aa.org and ask them to check how they're processing your meetings.

If an actionable error comes up, please come back we'll  see what we can do to explore that.

BTW, are you using the new Wagtail Meeting Guide?

**Comment by FlipperPA** [comment]
@tintinnabulate How large a region is being served? I know that the Meeting Guide app uses geofences. A quick glance at your Latitude and Longitude doesn't reveal anything out of whack. @tech2serve's suggestion to reach out to appsupport@aa.org is the right move; this is the feed we have in Philadelphia, and all of our meetings get picked up:

https://www.aasepia.org/meeting-guide/api/

I do note that you don't have `formatted_address` or `location` fields populated. I'm not sure if that affects the app.

**Comment by tintinnabulate** [comment]
@FlipperPA 

> Is there some specific error you're saying that makes you think this is related to the spec? If you're not getting errors (well, outside of the number of meetings showing up in the app), then my first guess would be the issue isn't related to the spec.

How do I see the errors? All I see is the absence of meetings in the App (i.e. 589 in Feed Validator, 120 in App)

> BTW, are you using the new Wagtail Meeting Guide?
No. Would that help diagnose the problem I'm seeing in the App? Is a meeting that is "valid" in the Feed Validator also "valid" in Wagtail MG?

**Comment by tintinnabulate** [comment]
@FlipperPA 

> How large a region is being served? I know that the Meeting Guide app uses geofences.
All of London. Are these Geofences published?

**Comment by tech2serve** [comment]
> @tech2serve
> 
> > Is there some specific error you're saying that makes you think this is related to the spec? If you're not getting errors (well, outside of the number of meetings showing up in the app), then my first guess would be the issue isn't related to the spec.
> 
> How do I see the errors? All I see is the absence of meetings in the App (i.e. 589 in Feed Validator, 120 in App)

For whatever browser you use, please search the Internet for how to turn on the developer or debugging console. Without debugging turned on for your website, any errors displayed there will likely be limited to the more egregious, but it can often be helpful nonetheless.

> 
> > BTW, are you using the new Wagtail Meeting Guide?
> 
> No. Would that help diagnose the problem I'm seeing in the App? Is a meeting that is "valid" in the Feed Validator also "valid" in Wagtail MG?
No. I had thought you might be using the new python-based meeting management system @FlipperPA has put together as an alternative to Wordpress and TSML. 

> @FlipperPA
> 
> > How large a region is being served? I know that the Meeting Guide app uses geofences.
> 
> All of London. Are these geofences published?

Not so much as they are controlled by GSO in NY. When someone sets up a new site, they need to coordinate with GSO to make sure the expected region is being imported, and the imported meetings are deconflicted with another site that might be reporting for the area.

So, I believe you still need to coordinate with GSO to resolve this issue (appsupport@aa.org).

**Comment by tintinnabulate** [comment]
@tech2serve 

> For whatever browser you use, please search the Internet for how to turn on the developer or debugging console.

It's the Meeting Guide app, which isn't in a browser, right? How do I turn on debugging console for the app?

**Comment by tech2serve** [comment]
I don't know that you can. Correct, the Meeting Guide app is coded for the iPhone or Android device. Not the website.

But, we aren't able to provide support for the Meeting Guide app, nor the backend service they control for aggregating and providing meeting information through the app. 

This repo is here for historical purposes, and to provide a place to discuss future directions of the specification. The Meeting Guide app is compliant with the spec listed here, and we expect GSO will keep it that way. TSML and Wagtail Meeting Guide are also compliant with this specification.

The issue you're describing is related to configuration settings controlled by GSO. I'd be happy to help you if I could; we simply do not have the insight or access to their system.

**Comment by FlipperPA** [comment]
@tintinnabulate This issue was closed, but I'm curious if it ended up being the geofencing issue with GSO. Did you happen to get in touch with GSO? If we need to dig deeper, I'm willing to help!
