### ISSUE TITLE
gzip/compress api response

### ISSUE THREAD

**Issue by arjunbanker** [code4recovery/spec#2]

**Comment by joshreisner** [comment]
hey arjun! you probably don't remember making this issue it was so long ago.

im closing it because i think this is probably the job of the API or service providing this spec, not the spec itself.

**Comment by arjunbanker** [comment]
hey! yes it’s been a while and i don’t remember this specific issue, seems
like it was tracking a task to ensure the http api response was gzipped,
would be more of a http server configuration issue - sounds good to close.
hope all is well on your end :)
