### ISSUE TITLE
Type addition request - Jail/Prison/Special Facility

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/spec#24]
Requesting additional type designator for indication that meeting either goes into or supports members of a Jail/Prison/Special Correction-DSHS Facility.  It is known there are many meetings behind the walls, so it is just a matter of making them easier to find.  In thinking about a fair & just abbreviation, the closest I could come up with was the 4 letter abbreviation for the committee that would be responsible for access to the facilities and knowledge of these meetings.
Desired abbreviation == CORR

**Comment by FlipperPA** [comment]
@jcookson-infoblox Howdy! I'm one of the volunteers here. I don't want you to think we're ignoring you. There are a few things we need to figure out going forward with meeting types.

We've tried to apply the 80/20 rule so far: only including meeting types that 80% of intergroups would use. Once a meeting type is in, it is in forever, and there are a few we regret having included in the past - which could be better suited for a description field.

We've tried to keep meeting types to be fields that people would want to actively search for: speaker meetings, big book, etc. We also have to coordinate with GSO on the app end any time we add any, to ensure the same list is included in the app. So it is a process.

Anyway, I hope that gives you some background on why this may take some time. We're meeting as a group tomorrow and I'll bring it up with the group to see what folks think moving forward with meeting types. They may be due for an overhaul.

**Comment by jcookson-infoblox** [comment]
Understood.  I know that you are trying coordinate things with GSO, thing take time and your efforts have meaningful impact on places that utilize this wonder set of tools you are making.  No worries on this end.  Take all the time you need.  Slow is fast.

**Comment by tech2serve** [comment]
Please see [this comment](https://github.com/code4recovery/spec/issues/22#issuecomment-847409253).
