### ISSUE TITLE
Type addition request : Chinese

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/spec#26]
Please add types relevant to Chinese languages.  Should be a couple, Chinese - Mandarin, Chinese - Cantonese & Chinese - Taiwan.  Recently attended PRAASA And one of the panels was translated into Chinese and the speaker indicated that their home group was local to their location in USA.  So, occurred to me that we should have minimally @ least 1 reference to Chinese - but thought I'd request the big 3.

**Comment by tech2serve** [comment]
Let's not accept languages as a type going forward in future specifications. Language is not a meeting type, rather it is part of the meeting culture and social situation; in a vast majority of cases, the language for a meeting is correctly determined by the site's configuration and physical location.

I suggest transferring your broader proposal about handling meetings as a separate data type over here to help start a discussion with GSO.

I'm going to close this issue in favor of what we've discussed on the TSML page. 

And reminder, for the near term, any group can add languages (or anything else) as types for their website. 

Thanks.
