### ISSUE TITLE
Type addition request - Slip Signed

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/spec#27]
It has been requested of me (as area 72 webmaster) to add a custom type for Slips Signed to our local meeting guide.
Am requesting that National consider adding this to the app base code.
Typically, this type of thing went (kind of) unsaid, but people needing their slips signed are having trouble finding meetings to accommodate them virtually.

**Comment by tech2serve** [comment]
Please see [this comment](https://github.com/code4recovery/spec/issues/22#issuecomment-847409253).
