### ISSUE TITLE
Update conference_url description

### ISSUE THREAD

**Issue by L-squared** [code4recovery/spec#35]
Hi - the current description

> is an optional URL to a specific public videoconference meeting. This should be a common videoconferencing service such as Zoom or Google Hangouts. It should launch directly into the meeting and not link to an intermediary page. Online meetings should still have a physical address, and types of ONL (Online Meeting) and TC (Temporary Closure). This spec is still for geographic meetings; options for online meetings are still in the planning stages.

Says that online meetings should still have a physical address and type of ONL and TC - I don't think that is accurate. Online meetings need an approximate address right? also the last sentence - "This spec is still for geographic meetings; options for online meetings are still in the planning stages." Should probably be removed

**Comment by joshreisner** [comment]
Thanks @L-squared !
