### ISSUE TITLE
Link on spec page is out of date

### ISSUE THREAD

**Issue by L-squared** [code4recovery/spec#37]
Hi all - I'm thinking we can remove the url shown on the spec page under **About** or redirect it to meetingguide.helpdocs.io
![image](https://user-images.githubusercontent.com/10970074/148095752-63d68906-587c-4b56-be6a-a285e9c6bb3f.png)

**Comment by joshreisner** [comment]
Ah, thanks. Link is removed now ⚡ 

In the readme we're still linking to meetingguide.aa.org/contact -- should we update that to https://meetingguide.helpdocs.io/article/jsydw3bxw8-connection-form now?

**Comment by L-squared** [comment]
Thanks Josh - well your question about contact made me realize its not so clear cut. I feel like this might be the best link if the idea is Getting People Connected: https://meetingguide.helpdocs.io/article/g0ykqkdq0u-connecting-to-meeting-guide-step-by-step - Alternately it may make sense to send them simply to the main support landing page - where there is a contact form (which I can't seem to link directly to yet) https://meetingguide.helpdocs.io/
