### ISSUE TITLE
disregard...sorry!

### ISSUE THREAD

**Issue by robskrob** [code4recovery/spec#54]

**Comment by robskrob** [comment]
sorry need to delete this!

**Comment by robskrob** [comment]
not needed

**Comment by joshreisner** [comment]
hi @robskrob sounds like a valid concern, but if you want you should be able to delete it at the bottom of the right column.

to answer the question, we screen conference_urls against patterns of known conference providers, to ensure that they link to safe, joinable services. if we need to add discord as a valid provider we can discuss that here or in the discussions area
