### ISSUE TITLE
Discord meetings appear as inactive

### ISSUE THREAD

**Issue by robanonservice** [code4recovery/spec#55]
Hello, we've been passing our spreadsheet [through the importer](https://sheets.code4recovery.org/), and then passing the JSON URL to our [instance of the plugin](https://github.com/code4recovery/tsml-ui) with a lot of success. However, we've come across one scenario where Discord meetings appear "in-active" under "Address / Platform" column of the plugin's UI. This in active state happens when:

- Meetings with a discord URL under `Conference URL`
- `Conference URL` is blank, but discord URL is present in `Notes`

According to the spec, Is there any way we can add a meeting that happens on Discord without it appear as "in active"?

**Comment by joshreisner** [comment]
hi @robanonservice could you give us some examples of discord URLs that you're entering?

**Comment by robanonservice** [comment]
hello @joshreisner ! Here is an example of the discord url: `https://discord.gg/N82qZVVaXk`

**Comment by joshreisner** [comment]
ok thanks do they all start with `https://discord.gg/` to your knowledge?

**Comment by robanonservice** [comment]
Yes to the best of my knowledge they all start like this: `https://discord.gg/`

**Comment by joshreisner** [comment]
ok we can add that pattern to our list of valid providers. this will make it show up in TSML UI like "Zoom" does with a camera icon.

are they sometimes video meetings? or audio only? or chat? or a combo?

**Comment by robanonservice** [comment]
Thank you, and good question. Here's the notes to one of the meetings:
> You must install the Discord app on your device and make an anonymous username when creating your Discord profile. 1 hour, voice with text chatting. We use Reaching for Personal Freedom and move thru Steps, Traditions, and Concepts on monthly schedule.

From what I can tell, the discord meeting appears to be mainly audio and chat. I will find out more and add what I learn here.

**Comment by joshreisner** [comment]
i think for now let's just add it as a valid provider with the camera icon, since we don't have other audio-only options. if people complain we can revisit it

**Comment by joshreisner** [comment]
try refreshing your list now with the discord URL in the `Conference URL` column

**Comment by robanonservice** [comment]
Nice thank you! I see the meeting now with a discord icon

**Comment by joshreisner** [comment]
Discord was added to 12 Step Meeting List as an officially-supported provider a few weeks ago - going to close now
