### ISSUE TITLE
NIA area 20 District 12 stopped working in the Chair

### ISSUE THREAD

**Issue by TedTdist12** [code4recovery/spec#71]
Hello,

Our district is not showing in the app for about a week now, can you tell us why?

Regrards,
Ted

**Comment by joshreisner** [comment]
Hi Ted!

Typically the best thing to do when asking about a connection to the Meeting Guide app is to email appsupport@aa.org, however I can actually see the issue in your case: the Day column in your spreadsheet has been accidentally renamed to "rclub" -- if you can rename it back to Day and refresh the feed on sheets.code4recovery.org, you should be back on the app within a few hours.

https://docs.google.com/spreadsheets/d/1cERocR4UEey_Hoq_pJkDI6XSLm2b-C0v6XyiSEiGWKQ/edit#gid=687617754
