### ISSUE TITLE
Support for listing online alternative

### ISSUE THREAD

**Issue by tintinnabulate** [code4recovery/spec#9]
In light of Covid-19 lockdowns, physical distancing etc...

If a meeting type is marked `TC` (i.e. has a Temporary Closure), could we allow meetings to publish an online alternative, with a clickable link to the online platform? e.g. Zoom, Google Meet, Skype etc.

I have no idea if I'm escalating this need in the right fashion, but I am noticing many meetings are currently discussing the need for online alternatives. I feel like it would be wise to streamline this so that physical meeting attendees can look up their usual meeting and find the online alternative on the same screen.

**Comment by joshreisner** [comment]
This is sort of a big question. I've been helping online intergroup rethink their meeting finder and move to a database over here: https://github.com/code4recovery/oiaa

The ultimate goal would be go get online meetings into the Meeting Guide app. For that, we'd need to create a fully new spec for online meetings (no address but yes timezone) and a new section of the app to list online meetings cares about time and not geolocation. (Pending GSO's approval.)

This is a weird situation though, where we want to enable meetings that *are* geographical to list an online alternative, so it might be as simple as adding a `video_conference_url` property to the feed to enable a button?

One concern Is that the URL is so open-ended, what if people used it for a Discourse website or Google group or Venmo account? I suppose we could annotate that it's only Zoom and Google Hangouts (and potentially others) for now?
